### ISSUE TITLE
Message signature not match the Public Key

### ISSUE THREAD

**Issue by Nortberg** [iotexproject/arduino-sdk#1]
Hi. As I'm trying to use IOTEX in my project to sign the messages we see that the signature of the same message using the same PK  differs on 2 functions and does not correspond to Public Key if I verify the signature and message hash on MEW.
Can You review the problem here?
see example;

void IoTeXsignMsg() { 
    std::string str = "{\"Name\":\"QmYXo5GgDuumVRu1C6qix8YHRkgLsmGcqTZ3kbe2mvkZGn\",\"Hash\":\"QmYXo5GgDuumVRu1C6qix8YHRkgLsmGcqTZ3kbe2mvkZGn\",\"Size\":\"31\"}";
    uint8_t message[192];
    std::copy(str.begin(), str.end(), std::begin(message));
    
    // here signature differs
    uint8_t signature[IOTEX_SIGNATURE_SIZE] = {0};
    signer.getSignature(message, sizeof(message), pkBytes, signature);

    // Print the signature
    Serial.print("Signature: ");
    for (int i=0; i<IOTEX_SIGNATURE_SIZE; i++)
    {
        char buf[3] = "";
        sprintf(buf, "%02x", signature[i]);
        Serial.print(buf);
    } 
    Serial.println("");

    // The hash differ every time
    uint8_t msgHash[IOTEX_HASH_SIZE] = {0};
    signer.getEthereumMessageHash(message, sizeof(message), msgHash);
     
     // Print the ETH hash
        Serial.print("ETH msg hash: ");
    for (int i=0; i<IOTEX_HASH_SIZE; i++)
    {
        char buf[3] = "";
        sprintf(buf, "%02x", msgHash[i]);
        Serial.print(buf);
    } 
    Serial.println("");
    
   // Here there is the other method 
    signature[0] = {0};
    signer.signHash(msgHash,pkBytes,signature);
    // Print the signature
    Serial.print("Signature: ");
    for (int i=0; i<IOTEX_SIGNATURE_SIZE; i++)
    {
        char buf[3] = "";
        sprintf(buf, "%02x", signature[i]);
        Serial.print(buf);
    }    
}

See here  getSignature() and signHash() different results.
10:24:41.933 -> Public key: 042c9b38918b2d1416ab9a37d724d0d2603bfa89a021a360b5aa32bad8aa83270aceb7c8e269e02540c05a993920450380add4562f68ffa6515864f895a6e1a42f
10:24:42.165 -> IoTeX address: io1hjwxp7fc60h3xlcdejj54m2cptfqfvul5yzevh
10:24:42.306 -> Ethereum address: 0xbc9c60f938d3ef137f0dcca54aed580ad204b39f
### **10:24:43.190 -> getSignature() result: ec0ad707da8a1915f6ff27b42cb5a397a138896009fc20c39619e5f621f5c1da7c60682441a3d39313fc818b339760598c1c93cdf761fcfc9c6a13f4f88b479301**
10:24:43.468 -> ETH msg hash: a9127ee30076a68d6aabd3c2176b67fb6ee7e069736bcd44232b4d2e3085dfa6
### **10:24:44.350 -> signHash() Signature: 2f8fe5b6dc5d221610ac90a63dc38b43794ee08a9d8134d770e33b52071705184f96833ece1a96ebb163ca6f1712f4e231b381d19ed9fde68fccccdbcc6a78c700**
10:24:45.330 -> Public Key: 042c9b38918b2d1416ab9a37d724d0d2603bfa89a021a360b5aa32bad8aa83270aceb7c8e269e02540c05a993920450380add4562f68ffa6515864f895a6e1a42f

sign verification on the wallet;
{
 "address": "0xbc9c60f938d3ef137f0dcca54aed580ad204b39f",
  "msg": "0xa9127ee30076a68d6aabd3c2176b67fb6ee7e069736bcd44232b4d2e3085dfa6",
  "sig": "ec0ad707da8a1915f6ff27b42cb5a397a138896009fc20c39619e5f621f5c1da7c60682441a3d39313fc818b339760598c1c93cdf761fcfc9c6a13f4f88b479301"
}

### **MEW verification fali:**
**0xae9d583096c0369f0469879bde84b3af60329ae9** did sign the message

or

{
 "address": "0xbc9c60f938d3ef137f0dcca54aed580ad204b39f",
  "msg": "0xa9127ee30076a68d6aabd3c2176b67fb6ee7e069736bcd44232b4d2e3085dfa6",
  "sig": "2f8fe5b6dc5d221610ac90a63dc38b43794ee08a9d8134d770e33b52071705184f96833ece1a96ebb163ca6f1712f4e231b381d19ed9fde68fccccdbcc6a78c700"
}

### **MEW verification fali:**
**0xe06204fb22868a7098794eada35b05fb165a05d0 did sign the message**

**Comment by Nortberg** [comment]
The only idea is coming there 
    uint8_t msgHash[### **IOTEX_HASH_SIZE]** = {0};
    signer.getEthereumMessageHash(message, sizeof(message), msgHash);
the eth hash size is 32 IOTEX_HASH_SIZEis also 32 or I'm understand wrong.

**Comment by Nortberg** [comment]
Problem solved I've made that here: uint8_t message[192] = {0};
Where I add a shorter string I had bunch of zeros at the end.

Comment; 
If You want to sign a message and let user to check the signature on ETH tools just use the json structure as bellow.
"address": "Your PUBLIC_KEY",
"msg":"Your message in HEX",
"sig": "signature in hex use signMessage(....) to get it"

{
  "address": "0xca50f5411b3b47d7ab0420e305583aee3e4d1e75",
  "msg": "0x7b224e616d65223a22516d59586f3547674475756d565275314336716978385948526b674c736d476371545a336b6265326d766b5a476e222c2248617368223a22516d59586f3547674475756d565275314336716978385948526b674c736d476371545a336b6265326d766b5a476e222c2253697a65223a223331227d00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "sig": "2f8fe5b6dc5d221610ac90a63dc38b43794ee08a9d8134d770e33b52071705184f96833ece1a96ebb163ca6f1712f4e231b381d19ed9fde68fccccdbcc6a78c700"
}

**Comment by Nortberg** [comment]
IoTeX that lib is superb.

**Comment by simonerom** [comment]
> IoTeX that lib is superb.

Thank you @Nortberg !
Feel free to contribute with issues, bug fixes or new features :)

**Comment by as-iotex** [comment]
> IoTeX that lib is superb.

Thanks for the feedback, and for using the library @Nortberg 

I am not sure I fully understand what the issue was. However let me try to clarify for future reference. Please correct me if I'm wrong

First issue:
I you were trying to pass a string to `getEthereumMessageHash()` and `getSignature()`
```
std::string str = "{"Name":"QmYXo5GgDuumVRu1C6qix8YHRkgLsmGcqTZ3kbe2mvkZGn","Hash":"QmYXo5GgDuumVRu1C6qix8YHRkgLsmGcqTZ3kbe2mvkZGn","Size":"31"}";
uint8_t message[192];

// The line below just stores the plain string into message
std::copy(str.begin(), str.end(), std::begin(message));
```

In order to obtain the same signature as with MEW, the plain string needs to be converted to a hex string before passing it to `getEthereumMessageHash()` and `getSignature()`


Second issue:

The length of the string `str` is 125 bytes. This is different than the size of `message` (192 bytes)
You are not initializing message, so it's contents are undefined. 
This could cause issues such as the signature differing between different runs of the program

```
std::string str = "{"Name":"QmYXo5GgDuumVRu1C6qix8YHRkgLsmGcqTZ3kbe2mvkZGn","Hash":"QmYXo5GgDuumVRu1C6qix8YHRkgLsmGcqTZ3kbe2mvkZGn","Size":"31"}";
uint8_t message[192];
```

The following ensures all "extra" bytes in `message` are set to 0
```
uint8_t message[192] = {0};
```
