### ISSUE TITLE
Message signature header byte

### ISSUE THREAD

**Issue by Nortberg** [iotexproject/arduino-sdk#2]
As I see every time I sign the message I get  last byte of signature as 01 or 00.

According to documentation last byte of signature is **### The header byte:** should be used as validator like this 
```
        int header = signatureData.getV() & 0xFF;
        // The header byte: 0x1B = first key with even y, 0x1C = first key with odd y,
        //                  0x1D = second key with even y, 0x1E = second key with odd y
```
        
So I must use code like that in case of using JAVA org.web3j.crypto
```
if (header < 27 || header > 34) {
            throw new SignatureException("Header byte out of range: " + header);
        }
```

As I saw You are implementing method signHash as bellow:
```
ResultCode Signer::signHash(const uint8_t hash[IOTEX_HASH_SIZE],
							const uint8_t private_key[IOTEX_PRIVATE_KEY_SIZE],
							uint8_t signature[IOTEX_SIGNATURE_SIZE])
{
	IOTEX_TRACE_F(logModule, "Signer::signHash()");
	if(ecdsa_sign_digest(&secp256k1, private_key, hash, signature, signature + 64, **### NULL**) != 0)
	{
		IOTEX_ERROR_F(logModule, "Error signing hash");
		return ResultCode::ERROR_SIGNATURE;
	}
	return ResultCode::SUCCESS;
}
```
Where last parameter of:
**ecdsa_sign_digest(&secp256k1, private_key, hash, signature, signature + 64, **### NULL**)** 
is NULL.

It looks like there is no option to get correct header byte.
Am I wrong?
it is limited by extern/crypto/ecdsa.h

I can make something like that 
```
   // Version of signature should be 27 or 28, but 0 and 1 are also possible versions
    if (v < 27) {
      v += 27;
    }
```

but not sure if it will impact the results in some cases.

**Comment by as-iotex** [comment]
Hi @Nortberg 

Could you elaborate on the problem you are seeing, and what you are trying to achieve?
It would be helpful if you can add some example code and the value you are getting vs the expected value

>According to documentation last byte of signature is ### The header byte: should be used as validator like this

Can you post a link to the documentation where this is mentioned?

Regards

**Comment by Nortberg** [comment]
Hi we are using spring gateway as a proxy to check consistency of incoming message (java)
In that case we use docs from here https://www.tabnine.com/code/java/classes/java.security.SignatureException

As We see the (v)ersion of signature is 01.
To accept that parameter in verification function We do that
```
 // Version of signature should be 27 or 28, but 0 and 1 are also possible versions
    if (v < 27) {
      v += 27;
    }
```
Then we can use implemented functions in org.web3j.crypto
Point is - if it is secure to do so.
Mean to get public key from signature R and S is important.
What about V - is there impact on results or not?

**Comment by as-iotex** [comment]
Could you share a minimum reproducible example of your embedded device program, and also the error log you are getting from the Java server?
Also please indicate what device you are using

May I ask you to do another test and check if you get the same error if you try to verify a message signed with the `ioctl` command line tool? 
Here are the docs for using it:
- Installation: https://docs.iotex.io/reference/ioctl-cli-reference/installation
- Signing a message: https://docs.iotex.io/reference/ioctl-cli-reference/accounts#sign-a-message

Thanks
