### ISSUE TITLE
Problem with ESP32 

### ISSUE THREAD

**Issue by keepy2018** [iotexproject/arduino-sdk#3]
There is multiple definition of `hmac_sha256'. Please can you solve? 
Best regards,
SL

/home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/wpa_supplicant/src/crypto/crypto_mbedtls.c:254: multiple definition of `hmac_sha256'; libraries/IoTeX-blockchain-client/extern/crypto/hmac.c.o:/Users/silviolanza/Documents/Arduino/libraries/IoTeX-blockchain-client/src/extern/crypto/hmac.c:63: first defined here
collect2: error: ld returned 1 exit status
exit status 1

**Comment by keepy2018** [comment]
I have solved commented the function void hmac_sha256() in libraries/IoTeX-blockchain-client/extern/crypto/hmac.c
/*
void hmac_sha256(const uint8_t *key, const uint32_t keylen, const uint8_t *msg,
                 const uint32_t msglen, uint8_t *hmac) {
  static CONFIDENTIAL HMAC_SHA256_CTX hctx;
  hmac_sha256_Init(&hctx, key, keylen);
  hmac_sha256_Update(&hctx, msg, msglen);
  hmac_sha256_Final(&hctx, hmac);
}
*/

**Comment by keepy2018** [comment]
The function is already defined here https://github.com/espressif/esp-idf/blob/master/components/wpa_supplicant/src/crypto/crypto_mbedtls.c

**Comment by keepy2018** [comment]
int hmac_sha256(const u8 *key, size_t key_len, const u8 *data,
		size_t data_len, u8 *mac)
{
	return hmac_sha256_vector(key, key_len, 1, &data, &data_len, mac);
}

**Comment by keepy2018** [comment]
OR better I have solved renamed the function void hmac_sha256() in libraries/IoTeX-blockchain-client/extern/crypto/hmac.c

void hmac_sha256(const uint8_t *key, const uint32_t keylen, const uint8_t *msg,
const uint32_t msglen, uint8_t *hmac) {
static CONFIDENTIAL HMAC_SHA256_CTX hctx;
hmac_sha256_Init(&hctx, key, keylen);
hmac_sha256_Update(&hctx, msg, msglen);
hmac_sha256_Final(&hctx, hmac);
}

in

void hmac_sha_256(const uint8_t *key, const uint32_t keylen, const uint8_t *msg,
const uint32_t msglen, uint8_t *hmac) {
static CONFIDENTIAL HMAC_SHA256_CTX hctx;
hmac_sha256_Init(&hctx, key, keylen);
hmac_sha256_Update(&hctx, msg, msglen);
hmac_sha256_Final(&hctx, hmac);
}

**Comment by as-iotex** [comment]
Hi @keepy2018 
We can't replicate the issue. The library examples build fine.

We need to know more details about your setup. The following would be useful:
- **Environment:** Arduino IDE / Arduino-cli / PlatformIO
- **OS:** Linux / Os X / Windows
- Does this happen if you try to build the example sketches (eg. IotexCommandLine)?
- Could you also post a minimum reproducible sketch and, if using PlatformIO, your `platformio.ini`?

**Comment by keepy2018** [comment]
Hello, I used Arduino IDE 1.8.18 and Board-manager ESP32 by Espressif Systems version 2.0.1.

**Comment by keepy2018** [comment]
on MAC OSX

**Comment by as-iotex** [comment]
Thank you, I was able to reproduce now
Fixed in the latest release (0.1.5). Please wait for a couple hours until the new release appears in the library manager and update your library.

Closing the issue, feel free to reopen if you still see it happpening
