### ISSUE TITLE
How to read data from smart contract?

### ISSUE THREAD

**Issue by keepy2018** [iotexproject/arduino-sdk#4]
Hello sir,
I have tried to write data to smart contract by the IoTex_ContractAddData example. But I cannot understand how to read/retrieve the data from smart contract for example to on/off led. Can you provide an example of IoTex_ContractReadData ? Thanks you.

Best regards,
SL

**Comment by keepy2018** [comment]
This is the ABI to interact with my smart contract example:
[{"inputs":[],"name":"retrieve","outputs":[{"internalType":"uint256","name":"num","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256","name":"num","type":"uint256"}],"name":"store","outputs":[],"stateMutability":"nonpayable","type":"function"}]

**Comment by keepy2018** [comment]
// SPDX-License-Identifier: GPL-3.0

pragma solidity >=0.5.0 <0.9.0;

/**
 * @title Storage
 * @dev Store & retrieve value in a variable
 */
contract Storage {

    uint256 number;

    /**
     * @dev Store value in variable
     * @param num value to store
     */
    function store(uint256 num) public {
        number = num;
    }

    /**
     * @dev Return value 
     * @return value of 'number'
     */
    function retrieve() public view returns (uint256){
        return number;
    }
}

**Comment by keepy2018** [comment]
I have tried something like this but doesn't work to read:
....
    // num
    uint8_t num[32];
    // Convert the privte key to a byte array
    uint8_t pk[IOTEX_PRIVATE_KEY_SIZE];
    signer.str2hex(pK, pk, IOTEX_SIGNATURE_SIZE);

    // Create the account 
    Account originAccount(pk);
    AccountMeta accMeta;
    char originIotexAddr[IOTEX_ADDRESS_C_STRING_SIZE] = "";

    // Get the account nonce
    originAccount.getIotexAddress(originIotexAddr);
    ResultCode result = connection.api.wallets.getAccount(originIotexAddr, accMeta);
    if (result != ResultCode::SUCCESS)
    {
        Serial.print("Error getting account meta: ");
        Serial.print(IotexHelpers.GetResultString(result));
    }
    int nonce = atoi(accMeta.pendingNonce.c_str());

    // Contruct the action
    // Create the parameters
    ParameterValue paramNum = MakeParamBytes(num, sizeof(num), true);

    // Create parameter values dictionary
    ParameterValuesDictionary params;
    params.AddParameter("num", paramNum);

    // Create the contract
    String abi = addDataAbiJson;
    Contract contract(abi);

    // Generate call data
    String callData = "";
    contract.generateCallData("retrieve", params, callData);
    Serial.print("Calling contract with data: 0x%");
    Serial.println(callData);

    uint8_t hash[IOTEX_HASH_SIZE] = {0};
    result = originAccount.sendExecutionAction(connection, nonce, 20000000, "1000000000000", "0", contractAddress, callData, hash);

    Serial.print("Result : ");
    Serial.println(IotexHelpers.GetResultString(result));
    if (result == ResultCode::SUCCESS)
    {
        Serial.print("Hash: ");
        for (int i=0; i<IOTEX_HASH_SIZE; i++)
        {
            char buf[3] = "";
            sprintf(buf, "%02x", hash[i]);
            Serial.print(buf);
        }
        Serial.println();

        Serial.println("num:");
        for  (int i=0; i<sizeof(num); i++)
        {
        Serial.print(num[0]);
        }
        Serial.println();
    }
....

**Comment by as-iotex** [comment]
ReadContract functionality is not implemented in the current release 
Marking this ticket as feature request

**Comment by as-iotex** [comment]
Planned for v0.2

**Comment by as-iotex** [comment]
Implemented in 0.2.2
See example of how to read a contract and decode data:
https://github.com/iotexproject/arduino-sdk/tree/main/examples/Xrc20TokenReadBalance
